### ISSUE TITLE
dac/tl_slick_spread.php needs to load Datacontainer 'tl_content' to work with internal cache of contao for contao-slick 1.3.5

### ISSUE THREAD

**Issue by webathlet** [heimrichhannot/contao-slick#25]
dca/tl_slick_spread.php needs to load Datacontainer 'tl_content' to work properly with activated internal cache of contao.

This issue appearead in the backend by using the gallery in for news posts. With activated internal cache a php error informs about the missing referenced tl_content.

`
\Controller::loadDataContainer('tl_content');`

**Comment by intradesign** [comment]
I have the same problem.

Another problem is that when you once activate the gallery you cannot deactivate it for the selected news item so you cannot go back to the news item's settings but see the error message each time – which makes deactivation impossible.

Will this be fixed in near future?

Thanks, Timo

**Comment by 2advance** [comment]
contao-slick/classes/Hooks.php: Line 73 add this:

`if($strName == 'tl_news')
            \Controller::loadDataContainer('tl_content');`

**Comment by fatcrobat** [comment]
Can you guys please check if version 1.6.2 fixes this issue?
