### ISSUE TITLE
Can't Create Thumb of slider

### ISSUE THREAD

**Issue by vishal1221** [heimrichhannot/contao-slick#29]
Hello
Can we display slider thumb?

**Comment by fatcrobat** [comment]
Yes you simply should create one slider as navigation (thumb) and one slider that contains the gallery images. Than conntect them by using the asNavFor Dropdown.

**Comment by vishal1221** [comment]
How can we create slider as navigation thumb ? Their is not option to create slider as navigation thumb
![slider](https://user-images.githubusercontent.com/16203151/42364803-1d02dca6-811a-11e8-930c-c4aa02074070.png)

**Comment by fatcrobat** [comment]
Create two slick configurations with asNavFor connectivity and create two slider elements. One slider is the nav (thumb) and one is the gallery.

**Comment by GMTeams** [comment]
Thanks for this useful info. Is there a way to navigate when the user clicks directly on the image, instead of "prev" and "next"? Now I have two sliders, and the first slider acts as the navigation for the second slider. But the navigation only works when I click "prev" or "next" in the first slider.

**Comment by GMTeams** [comment]
I found an working example in native slick and took the config into slick in contao and now it works :) I think it was the option "focusOnSelect". Thanks anyway!
